version: "3.1"

services:
  jenkins:
    image: jenkins/jenkins:2.361.3-lts-jdk11
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./data:/var/jenkins_home/
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker/daemon.json:/etc/docker/daemon.json
        #- /lib/x86_64-linux-gnu/libc.so.6:/lib/x86_64-linux-gnu/libc.so.6
      #- /usr/bin/strings:/usr/bin/strings
    networks:
      - devops

networks:
  devops:
    driver: bridge
    external: true